excluded:
  - Sources/MD5.swift # this dependency will be removed in the future version of the SDK
  - Carthage
  - Package.swift

identifier_name:
  excluded:
    - id

disabled_rules:
  - line_length
  - identifier_name

file_length:
  warning: 450
