excluded:
  - Sources/MD5.swift # this dependency will be removed in the future version of the SDK
  - Carthage
  - Package.swift

identifier_name:
  excluded:
    - id

disabled_rules:
  - line_length

# This generates a compiler error if more than this many SwiftLint warnings are present
# (This threshold can become more restrictive as remaining warnings are resolved via refactoring)
warning_threshold: 12